PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX HP: <http://purl.obolibrary.org/obo/HP_>
PREFIX IAO: <http://purl.obolibrary.org/obo/IAO_>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?hpo_id WHERE {
  ?hpo_id rdfs:subClassOf HP:0000118 . 
}